# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file
exporters:
  elasticsearch/trace:
    endpoints: [http://opensearch:9200]
    traces_index: trace_index
  elasticsearch/log:
    endpoints: [http://opensearch:9200]
    logs_index: my_log_index
service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch/log]
    traces:
      receivers: [otlp]
      exporters: [elasticsearch/trace]
      processors: [batch]